20220118 networking - master branch - PR 1 of 2
SensorsIot/IOTstack pull request #477
Opened 2022-01-18 02:07 UTC by Paraphraser

This PR follows on from [Issue 422](https://github.com/SensorsIot/IOTstack/issues/422#issuecomment-950149593) and the networking scheme proposed therein to support remote WireGuard clients obtaining DNS from ad-blockers (eg PiHole) running in another container on the same RPi as the WireGuard server.

This PR implements:

1. Two internal networks:

	* "default" (`iotstack_default` at runtime).
	* "nextcloud" (`iotstack_nextcloud` at runtime).

2. Docker allocates all IP addressing, dynamically, from 172.16/12 (reverting from 10/8 subnets).
3. NextCloud *explicitly* joins both internal networks.
4. NextCloud_DB *explicitly* joins "nextcloud".
5. All other containers *implicitly* join "default".
6. No networking differences between old and new menus (full harmonisation).
7. Resolves all remaining new-menu inconsistencies first raised in [Issue 245](https://github.com/SensorsIot/IOTstack/issues/245).

Adds `use-container-dns.sh` to WireGuard service template folder to support WireGuard forwarding DNS requests to ad-blockers running on the same RPi. This is based on work done by @ukkopahis. This change is related to the networking changes which deviate from the scheme proposed in Issue 422.

Documentation:

1. Adds "significant change to networking" to main README.md.
2. Updates WireGuard to explain how to forward DNS requests to ad-blockers running on the same RPi.

Signed-off-by: Phill Kelley <pmk.57t49@lgosys.com>

2022-01-18 08:24 UTC, ukkopahis requested changes

2022-01-18 08:24 UTC, ukkopahis commented on docs/Containers/WireGuard.md
> +	The default value of `auto` instructs the WireGuard *service* running within the WireGuard *container* to use the same DNS as the WireGuard *container* when resolving requests from connected peers.
Not exactly. PEERDNS=auto will use the **coredns** daemon running in the wireguard container, not the "docker container itself". Coredns is per default configured to use /etc/resolv.conf (from inside the container) which tells it to use 127.0.0.11 as the nameserver.

2022-01-18 08:24 UTC, ukkopahis commented on docs/Containers/WireGuard.md
> +	This configuration instructs WireGuard to forward DNS queries from remote peers to any **container** which is listening on port 53. This is the option you will want to choose if you are running an a
Please add something like:
And you don't want the pi host to use the pihole or adguardhome. If you have done the resolveconf.conf changes from the pihole docs, wireguard will out-of-the-box use any container providing dns service, and the custom-cont-init isn't needed.

2022-01-18 08:24 UTC, ukkopahis commented on docs/Containers/WireGuard.md
> +  # - PEERDNS=172.30.0.1
burn it with fire.  PEERDNS should never even be suggested to be 172.30.0.1

2022-01-18 08:24 UTC, ukkopahis commented on docs/Containers/WireGuard.md
> +	A third possibility is if you have a local upstream DNS server. You can specify the IP address of that server so that remote peers receive DNS resolution from that host. For example:
But preferably let coredns do dns forwarding if there is even the slimmest of chances the DNS server IP will change. Changes to the PEERDNS are not propagated to existing clients. It's much easier to just maintain where DNS is forwarded on the server than to change every Wireguard client.

2022-01-18 15:22 UTC, ukkopahis commented
Also from file .templates/domoticz/service.yml remove line:
```
  network_mode: bridge
```
(network mode defaults to bridge, no need to restate that)

2022-01-19 10:16 UTC, Slyke commented on .templates/dashmachine/service.yml
> +
It's generally good practice to have an empty line at the end of the file. It's possible @Paraphraser 's linter did this automatically.

2022-01-19 10:17 UTC, Slyke approved these changes

2022-01-19 10:19 UTC, merged